<div class="col connectedSortable">
    <div class="card mb-4">
        <div class="card-header">
            <h2 class="card-title"><?=$list['list_name']?></h2>
            <div class="card-tools">
                <span title="X Current Contacts" class="badge text-bg-primary">0</span>
                <button type="button" class="btn btn-tool" data-lte-toggle="card-collapse">
                    <i data-lte-icon="expand" class="bi bi-plus-lg"></i>
                    <i data-lte-icon="collapse" class="bi bi-dash-lg"></i>
                </button>
                <button type="button" class="btn btn-primary btn-sm">
                    <span>New Contact</span>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="connectedSortable">

            </div>
        </div>
    </div>
</div>