<div class="modal-content">
<?php
if (isset($this->form)):
?>
<div class="modal-header">New Contact</div>
<div class="modal-body">
    <?=$this->form($this->form)?>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    <button form="<?=$this->form->getAttribute('id')?>" type="submit" class="btn btn-primary">Save</button>
</div>
<?php
endif;
?>
</div>