<div class="modal-dialog modal-dialog-centered modal-sm">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="loginModalLabel">New List</h1>
        </div>
        <div class="modal-body">
            <form id="list-form" action="<?=$this->url('contact.create.list')?>" method="post">
                <div class="input-group mb-3">
                <input name="list_name" type="text" class="form-control" placeholder="List Name">
                </div>
            </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button id="create-list-modal-submit" type="button" class="btn btn-primary">Save</button>
        </div>
    </div>
</div>