<?php
// todo: add a id="contact_$id" to allow targeting a specific contact post update
?>
<div id="contact_<?=$this->contact->id?>" class="card mb-4" data-contact-id="<?=$this->contact->id?>">
    <div class="card-header">
        <h3 class="card-title"><?=$this->contact->first_name . ' ' . $this->contact->last_name?></h3>
        <div class="card-tools">
            <button
                hx-get="<?=$this->url('cm.contact', ['list_id' => $this->contact->list_id, 'id' => $this->contact->id])?>"
                hx-target="#dialog"
                type="button"
                class="btn btn-primary btn-sm">
                <i class="bi bi-pencil-square"></i>
            </button>
            <button
                hx-delete="<?=$this->url('cm.contact', ['list_id' => $this->contact->list_id, 'id' => $this->contact->id])?>"
                hx-target="#contact_<?=$this->contact->id?>"
                hx-swap="outerHTML"
                hx-confirm="Are you sure you want to delete this contact?"
                type="button"
                class="btn btn-primary btn-sm">
                <i class="bi bi-trash3"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Email: <?=$this->contact->email?></li>
        </ul>
    </div>
</div> <!-- /.card -->

