<div class="app-content-header"> <!--begin::Container-->
    <div class="container-fluid"> <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="mb-0">Contact Manager</h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Dashboard
                    </li>
                </ol>
            </div>
        </div> <!--end::Row-->
    </div> <!--end::Container-->
</div> <!--end::App Content Header--> <!--begin::App Content-->
<div class="app-content"><!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <!--begin::Col-->
            <div class="col-sm-1 col-1 mb-4">
                <button id="create-list-modal-button" data-bs-toggle="modal" data-bs-target="create-list-modal" type="button" class="btn btn-primary btn-md">New List</button>
            </div><!--end::Col-->
        </div><!--end::Row-->
        <!--begin::Row-->
        <div class="row justify-content-around"> <!-- Start col -->
            <?php
            if (isset($this->list) && count($this->list) > 0):
                foreach ($this->list as $list):
            ?>
                <div class="col-lg-3 text-bg-secondary connectedSortable">
                    <span><?=$list['list_name']?></span>
                    <?php
                    foreach ($this->contacts as $contact):
                        if ($contact['list_name'] === $list['list_name']):
                    ?>
                    <div class="card mb-4">
                        <div class="card-header">
                            <h3 class="card-title"><?=$contact['first_name']?></h3>
                        </div>
                        <div class="card-body">
                            <div id="revenue-chart"></div>
                        </div>
                    </div> <!-- /.card -->
                    <?php
                        endif;
                    endforeach;
                    ?>
                </div>
            <?php
                endforeach;
            endif;
            ?>
        </div> <!-- /.row (main row) -->
    </div> <!--end::Container-->
</div> <!--end::App Content-->