<div class="app-content-header"> <!--begin::Container-->
    <div class="container-fluid"> <!--begin::Row-->
        <div class="row">
            <div class="col-sm-6">
                <h3 class="mb-0">Contact Manager</h3>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-end">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Dashboard
                    </li>
                </ol>
            </div>
        </div> <!--end::Row-->
    </div> <!--end::Container-->
</div> <!--end::App Content Header--> <!--begin::App Content-->
<div class="app-content"><!--begin::Container-->
    <div class="container-fluid">
        <!--begin::Row-->
        <div class="row">
            <!--begin::Col-->
            <div class="col-sm-1 col-1 mb-4">
                <button id="create-list-modal-button" data-bs-toggle="modal" data-bs-target="create-list-modal" type="button" class="btn btn-primary btn-md">New List</button>
            </div><!--end::Col-->
        </div><!--end::Row-->
        <!--begin::Row-->
        <div id="list-board" class="row row-cols-2 row-cols-lg-4 g-2 g-lg-3"> <!-- Start col -->
            <?php
            if (isset($this->list) && count($this->list) > 0):
                $contactCount = 0;
                foreach ($this->list as $list):
            ?>
                <div id="list_<?=$list['id']?>" class="col">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h2 class="card-title"><?=$list['list_name']?></h2>
                            <div class="card-tools">
                                <span title="X Current Contacts" class="badge text-bg-primary"><?=$contactCount?></span>
                                <button type="button" class="btn btn-tool" data-lte-toggle="card-collapse">
                                    <i data-lte-icon="expand" class="bi bi-plus-lg"></i>
                                    <i data-lte-icon="collapse" class="bi bi-dash-lg"></i>
                                </button>
                                <button type="button" role="button" data-cmlist-id="<?=$list['id']?>" class="create-contact-button btn btn-primary btn-sm">
                                    <span>New Contact</span>
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="connectedSortable">
                                <?php
                                foreach ($this->contacts as $contact):
                                    if ($contact['list_name'] === $list['list_name']):
                                ?>
                                    <div class="card mb-4">
                                        <div class="card-header">
                                            <h3 class="card-title"><?=$contact['first_name'] . ' ' . $contact['last_name']?></h3>
                                        </div>
                                        <div class="card-body">
                                            <div id="revenue-chart"></div>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">Email: <?=$contact['email']?></li>
                                        </ul>
                                    </div> <!-- /.card -->
                                <?php
                                    endif;
                                endforeach;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php
                endforeach;
            endif;
            ?>
        </div> <!-- /.row (main row) -->
    </div> <!--end::Container-->
</div> <!--end::App Content-->