<?php

declare(strict_types=1);

$this->headMeta()
    ->setCharSet('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

$this->headLink(
    [
        'rel'  => 'shortcut icon',
        'href' => 'https://getlaminas.org/images/favicon/favicon.ico',
    ]
);

$this->headLink()
    ->appendStylesheet(
        'https://cdn.jsdelivr.net/npm/@fontsource/source-sans-3@5.0.12/index.css',
        'screen',
        '',
        [
            'integrity'   => 'sha256-tXJfXfp6Ewt1ilPzLDtQnJV4hclT9XuaZUKyUvmyr+Q=',
            'crossorigin' => 'anonymous'
        ]
    )->appendStylesheet(
        'https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/styles/overlayscrollbars.min.css',
        'screen',
        '',
        [
            'integrity'   => 'sha256-dSokZseQNT08wYEWiz5iLI8QPlKxG+TswNRD8k35cpg=',
            'crossorigin' => 'anonymous',
        ]
    )->appendStylesheet(
        'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.min.css',
        'screen',
        '',
        [
            'integrity'   => 'sha256-Qsx5lrStHZyR9REqhUF8iQt73X06c8LGIUPzpOhwRrI=',
            'crossorigin' => 'anonymous',
        ]
    )->appendStylesheet(
        $this->basePath('css/adminlte.css'), // local styles
        'screen'
    )->appendStylesheet(
        'https://cdn.jsdelivr.net/npm/apexcharts@3.37.1/dist/apexcharts.css',
        'screen',
        '',
        [
            'integrity'   => 'sha256-4MX+61mt9NVvvuPjUWdUdyfZfxSB1/Rf9WtqRHgG5S0=',
            'crossorigin' => 'anonymous',
        ]
    )->appendStylesheet(
        'https://cdn.jsdelivr.net/npm/jsvectormap@1.5.3/dist/css/jsvectormap.min.css',
        'screen',
        '',
        [
            'integrity'   => 'sha256-+uGLJmmTKOqBr+2E6KDYs/NRsHxSkONXFHUL0fy2O/4=',
            'crossorigin' => 'anonymous',
        ]
    );

$this->inlineScript()
    ->appendFile(
        'https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/browser/overlayscrollbars.browser.es6.min.js',
        '',
        [
            'integrity'   => 'sha256-H2VM7BKda+v2Z4+DRy69uknwxjyDRhszjXFhsL4gD3w=',
            'crossorigin' => 'anonymous',
        ],
    )->appendFile(
        'https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js',
        '',
        [
            'integrity'   => 'sha256-whL0tQWoY1Ku1iskqPFvmZ+CHsvmRWx/PIoEvIeWh4I=',
            'crossorigin' => 'anonymous',
        ],
    )->appendFile(
        'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js',
        '',
        [
            'integrity'   => 'sha256-YMa+wAM6QkVyz999odX7lPRxkoYAan8suedu4k2Zur8=',
            'crossorigin' => 'anonymous',
        ],
    )->appendFile(
        $this->basePath('js/adminlte.js')
    )->appendScript(
        'const SELECTOR_SIDEBAR_WRAPPER = ".sidebar-wrapper";
        const Default = {
            scrollbarTheme: "os-theme-light",
            scrollbarAutoHide: "leave",
            scrollbarClickScroll: true,
        };
        document.addEventListener("DOMContentLoaded", function() {
            const sidebarWrapper = document.querySelector(SELECTOR_SIDEBAR_WRAPPER);
            if (
                sidebarWrapper &&
                typeof OverlayScrollbarsGlobal?.OverlayScrollbars !== "undefined"
            ) {
                OverlayScrollbarsGlobal.OverlayScrollbars(sidebarWrapper, {
                    scrollbars: {
                        theme: Default.scrollbarTheme,
                        autoHide: Default.scrollbarAutoHide,
                        clickScroll: Default.scrollbarClickScroll,
                    },
                });
            }
        });'
    )->appendFile(
        'https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js',
        '',
        [
            'integrity'   => 'sha256-ipiJrswvAR4VAx/th+6zWsdeYmVae0iJuiR+6OqHJHQ=',
            'crossorigin' => 'anonymous',
        ],
    )->appendScript(
        '        const connectedSortables =
            document.querySelectorAll(".connectedSortable");
        connectedSortables.forEach((connectedSortable) => {
            let sortable = new Sortable(connectedSortable, {
                group: "shared",
                handle: ".card-header",
            });
        });

        const cardHeaders = document.querySelectorAll(
            ".connectedSortable .card-header",
        );
        cardHeaders.forEach((cardHeader) => {
            cardHeader.style.cursor = "move";
        });'
    )->appendFile(
        'https://cdn.jsdelivr.net/npm/apexcharts@3.37.1/dist/apexcharts.min.js',
        '',
        [
            'integrity'   => 'sha256-+vh8GkaU7C9/wbSLIcwq82tQ2wTf44aOHA8HlBMwRI8=',
            'crossorigin' => 'anonymous',
        ]
    )->appendFile(
        'https://cdn.jsdelivr.net/npm/jsvectormap@1.5.3/dist/js/jsvectormap.min.js',
        '',
        [
            'integrity'   => 'sha256-/t1nN2956BT869E6H4V1dnt0X5pAQHPytli+1nTZm2Y=',
            'crossorigin' => 'anonymous',
        ]
    );
?>
<?=$this->doctype();?>
<html>
<head>
    <base href="<?=$this->basePath('/');?>" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?=$this->headTitle('Hop Project')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
    <body class="<?=$this->bodyClass();?>">
        <?=$this->content?>
    <?=$this->inlineScript()?>
    </body>
</html>