<?php

declare(strict_types=1);

$this->headMeta()
    ->setCharSet('UTF-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1')
    ->appendName('color-scheme', 'light dark')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

$this->headLink(
    [
        'rel'  => 'shortcut icon',
        'href' => 'https://getlaminas.org/images/favicon/favicon.ico',
    ]
);
// styles
$this->headLink()
    ->appendStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.green.min.css');
// head script files and script

$this->headScript()
->appendFile(
    'https://unpkg.com/htmx.org@2.0.1/dist/htmx.js',
    'text/javascript',
    [
        'integrity' => 'sha384-gpIh5aLQ0qmX8kZdyhsd6jA24uKLkqIr1WAGtantR4KsS97l/NRBvh8/8OYGThAf',
        'crossorigin' => 'anonymous',
    ],
)->appendScript(
    $this->htmxConfig,
    '',
    ['noescape' => true]
);

// inline script which is printed at bottom of page
$this->inlineScript()
    ->appendFile('https://code.jquery.com/jquery-3.5.1.min.js');
?>
<?=$this->doctype();?>

<html>
<head>
    <base href="<?=$this->basePath('/');?>" />
    <?=$this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
</head>
<body>
    <header id="app-header" class="container">
        <nav>
            <!-- Brand -->
            <ul>
                <li>
                    <a href="<?=$this->url('home')?>">
                        <img src="https://docs.laminas.dev/img/laminas-mezzio-rgb.svg" alt="Laminas Mezzio" width="300" />
                    </a>
                </li>
            </ul>
            <!-- Links -->
            <ul>
                <li>
                    <a href="https://docs.mezzio.dev/mezzio" target="_blank">
                        <i class="fa fa-book"></i> Docs
                    </a>
                </li>
                <li>
                    <a href="https://github.com/mezzio/mezzio" target="_blank">
                        <i class="fa fa-wrench"></i> Contribute
                    </a>
                </li>

                <li>
                    <a href="<?=$this->url('api.ping')?>">
                        Ping Test
                    </a>
                </li>
                <?php
                if ($this->user->getDetail('role_id') === 'Administrator'):
                ?>
                <li>
                    <a href="<?=$this->url('admin')?>">
                        Admin
                    </a>
                </li>
                <?php
                endif;
                ?>
                <?php
                if ($this->user->getIdentity() === 'guest'):
                ?>
                <li>
                    <a href="<?=$this->url('login')?>">
                        Sign In
                    </a>
                </li>
                <?php
                else:
                ?>
                <li>
                    <a href="<?=$this->url('logout')?>">
                        Sign Out
                    </a>
                </li>
                <?php
                endif;
                ?>
            </ul>
        </nav>
    </header>
    <main class="container">
        <?=$this->content?>
    </main>
    <footer id="app-footer" class="container">
        <hr />
        <p>
            &copy; <?=date('Y')?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
        </p>
    </footer>
    <?=$this->inlineScript()?>
</body>
</html>
