<?php

declare(strict_types=1);

//$this->headTitle(ucfirst($this->currentRoute));
$this->bodyClass('login-page bg-body-secondary');
?>
<section class="inner-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 ms-auto">
                <?php
                    if (isset($this->error)) {
                        // show an error
                    }

                    if (isset($this->form)) {
                        $this->form->setAttribute('action', $this->url('login'));
                        // $this->form->addSubmit(
                        //     priority: -1,
                        //     showText: 'Login',
                        //     class: 'btn btn-md btn-info text-light'
                        // );
                        echo $this->form($this->form);
                    }
                ?>
            </div>
        </div>
    </div>
</section>
