<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            ContactManager\Handler\CreateContactHandler::class => ContactManager\Handler\CreateContactHandlerFactory::class,
            ContactManager\Handler\CreateListHandler::class => ContactManager\Handler\CreateListHandlerFactory::class,
            ContactManager\Handler\DashboardHandler::class => ContactManager\Handler\DashboardHandlerFactory::class,
            ContactManager\Handler\LandingHandler::class => ContactManager\Handler\LandingHandlerFactory::class,
        ],
    ],
];
